server.port=8090
spring.application.name=ms-checkin

spring.datasource.url=jdbc:mysql://localhost:3306/checkin_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

config.ms-tickets.url=http://localhost:8084/api/tickets
config.ms-ordenes.url=http://localhost:8085/api/ordenes
