# Puerto y Nombre del Servicio
server.port=8081
spring.application.name=ms-autenticacion

# Evita la caida por el config del server, ademas que debe ser obligatorio
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false

# ConexiÃ³n a Base de Datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/db_autenticacion?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ConfiguraciÃ³n de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Propiedades de tu Token JWT: Para la logica del login con el token
jwt.secret=EstaEsUnaClaveSecretaMuyLargaYSeguraParaElProyecto2026
jwt.expiration=86400000

# ConfiguraciÃ³n de Logs: Alineado con tu paquete cl.eventos.ms_autenticacion
logging.level.root=INFO
logging.level.cl.eventos.ms_autenticacion=DEBUG
logging.file.name=logs/ms-autenticacion.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Conexion con el servidor de Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
