# Puerto
server:
  port: 8083

# Nombre del Microservicio
spring:
  application:
    name: ms-eventos
  
  # Desactivar autoconfiguración de Config Server
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

  # Configuración de Base de Datos MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/eventos_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Configuración de Hibernate / JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Configuración de Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Configuración de Swagger UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method # Ordena los métodos (GET, POST, etc.)
