spring.application.name=ms-pagos
server.port=8086

spring.datasource.url=jdbc:mysql://localhost:3306/pagos_db
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

config.ms-ordenes.url=http://localhost:8085/api/ordenes
logging.level.cl.eventos.ms_pagos.client=DEBUG
