eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://ms-eureka-server:8761/eureka/}

logging:
  level:
    root: WARN
    cl.eventos.ms_autenticacion: INFO
  file:
    name: logs/ms-autenticacion-prod.log
